[package]
name = "accelerator"
version = "0.1.0"
edition = "2021"

[lib]
name = "accelerator"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.27.2", features = ["extension-module"] }
regex = "1.10.0"
memmap2 = "0.9.0"
glob = "0.3.1"
